shell /usr/bin/zsh

# Audible bell
enable_audio_bell no

# Window layout
remember_window_size  no
# initial_window_width  640
# initial_window_height 400
initial_window_width  100c
initial_window_height 24c

enabled_layouts horizontal

# Window padding
window_padding_width 5 8

# Font family
font_family      JetBrainsMono Nerd Font Mono
bold_font        auto
italic_font      auto
bold_italic_font auto

# Font size
font_size	 11.0

# Window decorations
hide_window_decorations yes
# linux_display_server x11

# Tabs
tab_bar_edge bottom
tab_bar_style powerline
tab_powerline_style angled
# tab_bar_style slant

# Vertical split
# map ctrl+alt+v launch --location=vsplit
# split_axis --location horizontal
# map f6 launch --location=vsplit
# map f5 launch --location=hsplit

# BEGIN_KITTY_THEME
# Tokyo Night
include current-theme.conf
# END_KITTY_THEME
